# U-Boot extlinux boot configuration for Rockchip RK3576

label Ubuntu 24.04 LTS (overlay)
    kernel /boot.img
    fdt /dtbs/myd-lr3576.dtb
    fdtoverlays /overlays/myd-lr3576-display.dtbo
    append earlycon=uart8250,mmio32,0x2a340000 console=ttyFIQ0,1500000n8 ro rootwait root=PARTLABEL=rootfs rootfstype=ext4

label Ubuntu 24.04 LTS (overlay, console only)
    kernel /boot.img
    fdt /dtbs/myd-lr3576.dtb
    append earlycon=uart8250,mmio32,0x2a340000 console=ttyFIQ0,1500000n8 ro rootwait root=PARTLABEL=rootfs rootfstype=ext4 nosplash
